name: cicd_login_react

on:
  push:
    branches:
      - cicd_branch

jobs:
# Goal : To checkout code, test linting and then push to docker hub
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./outstaff-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/login-react-frontend:latest

      - name: Docker Build and Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/login-react-backend:latest

# Goal : To deploy the built images from Ci steps, after the completion of CI

  docker-cd:
    runs-on: self-hosted
    needs: docker-ci
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy the containers using docker compose
        run: |
          docker compose down
          docker compose pull
          docker compose up -d --force-recreate

